import assert from "node:assert/strict";
import test from "node:test";
import { consumeOAuthDestination, rememberOAuthDestination, oauthReturnFromUrl, OAUTH_DESTINATION_KEY, OAUTH_DESTINATION_TTL } from "../lib/oauthReturn.ts";
function store() { const values = new Map<string, string>(); return { getItem: (k: string) => values.get(k) ?? null, setItem: (k: string, v: string) => { values.set(k, v); }, removeItem: (k: string) => { values.delete(k); } }; }
test("implicit return metadata does not retain tokens", () => { const result = oauthReturnFromUrl("https://www.calsie.com.au/#access_token=secret&refresh_token=secret&type=signin"); assert.deepEqual(result, { kind: "session" }); assert.ok(!JSON.stringify(result).includes("secret")); });
test("ordinary home and unrelated anchors do not trigger recovery", () => { for (const href of ["https://www.calsie.com.au/", "https://www.calsie.com.au/#pricing"]) assert.equal(oauthReturnFromUrl(href).kind, "none"); });
test("recovery and signup are not treated as Google sign-in", () => { for (const type of ["recovery", "signup"]) assert.equal(oauthReturnFromUrl(`https://www.calsie.com.au/#access_token=a&refresh_token=b&type=${type}`).kind, "none"); });
test("provider cancellation is distinguished from success", () => { assert.equal(oauthReturnFromUrl("https://www.calsie.com.au/#error=access_denied").kind, "error"); });
test("code return is forwarded to existing callback", () => { assert.deepEqual(oauthReturnFromUrl("https://www.calsie.com.au/?code=one-time-code"), { kind: "code", code: "one-time-code" }); });
test("saved purchase destination is restored once", () => { const storage = store(); const next = "/payment?restoreIntent=1"; rememberOAuthDestination(next, storage, 100); assert.equal(consumeOAuthDestination(storage, 101), next); assert.equal(consumeOAuthDestination(storage, 102), null); });
test("external destinations are rejected", () => { const storage = store(); rememberOAuthDestination("//attacker.test", storage, 100); assert.equal(consumeOAuthDestination(storage, 101), "/dashboard?panel=overview"); });
test("stale, future and malformed records are discarded", () => { const storage = store(); rememberOAuthDestination("/payment", storage, 100); assert.equal(consumeOAuthDestination(storage, 100 + OAUTH_DESTINATION_TTL + 1), null); rememberOAuthDestination("/payment", storage, 200); assert.equal(consumeOAuthDestination(storage, 100), null); storage.setItem(OAUTH_DESTINATION_KEY, "broken"); assert.equal(consumeOAuthDestination(storage), null); });
test("blocked storage does not break OAuth", () => { const storage = { getItem() { throw new Error("blocked"); }, setItem() { throw new Error("blocked"); }, removeItem() { throw new Error("blocked"); } }; rememberOAuthDestination("/payment", storage); assert.equal(consumeOAuthDestination(storage), null); rememberOAuthDestination("/payment", null); assert.equal(consumeOAuthDestination(null), null); });
